### ISSUE TITLE
Agent is een prov:Agent

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#1]
ipv een dcterms:Agent

wegens

prov:wasAssociatedWith
        rdfs:domain             prov:Activity ;
        rdfs:range              prov:Agent .

**Comment by brechtvdv** [comment]
Zie https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Agent
