### ISSUE TITLE
Wat is Locatie als datatype?

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#12]
Indien Locatie verwijst naar prov:Location, is dat toch gewoon een klasse?

![Locatie_als_datatype](https://github.com/Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving/assets/28095014/dc16f58c-6cfe-4be1-9e38-5cb3ae06e9be)

**Comment by brechtvdv** [comment]
Aangepast naar klasse

**Comment by brechtvdv** [comment]
Opgelost: 
<img width="403" alt="image" src="https://github.com/user-attachments/assets/0e1917de-2224-41a7-a35d-4ac747abcafd">
