### ISSUE TITLE
Tekstfout in inleiding: gemeente zonder gemeenteHUIS

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#15]
In de inleidende tekst staat "gemeente zonder gemeente". "-huis" ontbreekt.

**Comment by brechtvdv** [comment]
Aangepast (nieuwe publicatie volgt)

**Comment by brechtvdv** [comment]
Opgelost in https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving
<img width="854" alt="image" src="https://github.com/user-attachments/assets/d457148d-c1ae-4a40-afe2-450ab66dfc56">
