### ISSUE TITLE
"opinie" in definitie adviesvraag

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#17]
Adviesvraag is gedefinieerd als “vraag om een opinie”.
Waarom niet “vraag om een advies”?
Opinie heeft toch wel een licht andere betekenis.

**Comment by brechtvdv** [comment]
Voorstel: "vraag om raadgeving"

We willen vermijden dat de term "Advies" in de definitie wordt gebruikt.

**Comment by PhR-VO** [comment]
Wat lost dat op?
Daarbij: een adviesvraag is een formeel iets. Dit formele karakter komt in deze definitie niet tot uitdrukking.

**Comment by brechtvdv** [comment]
Is "raadgeving" geworden:
Vraag aan een organisatie of persoon om een raadgeving die bijdraagt aan het beslissingsproces
https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Adviesvraag
