### ISSUE TITLE
Definitie datum antwoord verwacht

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#18]
volgens de definitie is dit de datum **waarop** het antwoord verwacht wordt? Is het niet eerder een deadline/ uiterste datum, kortom de datum **waartegen** het antwoord verwacht wordt?

**Comment by brechtvdv** [comment]
Aangepast (nieuwe publicatie volgt)

**Comment by brechtvdv** [comment]
Zie: https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Initiatiefrechtvraag
