### ISSUE TITLE
Annotation - selector - shacl selector

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#19]
Kan je een voorbeeld geven van hoe dit in geval van de slimme raadpleegomgeving gebruikt zal worden aub?

**Comment by brechtvdv** [comment]
Enkele voorbeelden toegevoegd:
https://github.com/Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving/blob/main/README.md#besluit-annoteren-met-resource-locatie
https://github.com/Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving/blob/main/README.md#tekstpositieselector
https://github.com/Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving/blob/main/README.md#shaclpathselector
