### ISSUE TITLE
property genereert is niet gedefinieerd 

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#2]
waarschijnlijk prov:generated
Relatie tussen Activiteit en Annotatie

**Comment by brechtvdv** [comment]
Definitie toegevoegd: De annotatie die werd aangemaakt als gevolg van de activiteit.
Subproperty van prov:generated
https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/kandidaatstandaard/2024-10-14/#Activiteit(annotaties)
