### ISSUE TITLE
concept "recht" wordt ontleend aan een ontologie uit een totaal ander domein. Is dat handig?

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#20]
De valkuil van deze aanpak is dat je allemaal andere aspecten, zoals properties, die binnen de andere domein-specifieke ontologie bepaald zijn en wellicht zinvol zijn, binnentrekt, terwijl ze binnen het eigen toepassingsgebied niet per se zinvol zijn. Nader te verklaren.

**Comment by brechtvdv** [comment]
FLINT gebruiken we niet meer. Vervangen door OSLO omgevingsvergunning: https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Recht
