### ISSUE TITLE
crm:P2_has_type

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#21]
Als property op Recht. (met als range definitie  skos:Concept)
Gebruik hier eens gewoon dct:type aub.
Wat is het nut van de range en domain definitie op crm:P2_has_type?

**Comment by brechtvdv** [comment]
Was afkomstig van https://data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-object/#Recht

Recht wordt nu gebruikt van https://data.vlaanderen.be/ns/omgevingsvergunning/#Recht wat beter aansluit van domein.
