### ISSUE TITLE
Notificatiebericht en property url

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#25]
```
<https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/ontwerpstandaard/2023-11-06#NotificatieberichtShape> a shacl:NodeShape;
  shacl:closed false;
  shacl:property [
    shacl:class <https://data.europa.eu/eli/ontology#LegalExpression>;
    shacl:description "Link naar de legale verschijingsvorm."@nl;
    shacl:maxCount 1;
    shacl:name "url"@nl;
    shacl:path schema:url
  ];
  shacl:targetClass <https://data.vlaanderen.be/ns/notificatie#Notificatiebericht> .
```
1. Een property met betekenis aub.
2. Ik lees in de beschrijving het volgende: Er is een relatie voorzien tussen Notificatiebericht en Legale Verschijningsvorm. Dit is relevant voor applicaties die doelgroepen willen informeren over besluiten die genomen werden. Voor de verdere uitwerking verwijzen we door naar de [OSLO Notificatie Basis](https://data.vlaanderen.be/standaarden/erkende-standaard/applicatieprofiel-notificatie-basis.html) standaard. 
https://data.vlaanderen.be/doc/applicatieprofiel/notificatie-basis/#Notificatiebericht%3Aurl

url heeft hier range http://www.w3.org/2001/XMLSchema#anyURI met beschrijving: De url kan gebruikt worden om een doorverwijzing mee te geven naar een resource waarop het Notificatiebericht betrekking heeft.

- http://www.w3.org/2001/XMLSchema#anyURI is een literal en geen resource 
- een legale verschijningsvorm instance is nooit een literal

**Comment by brechtvdv** [comment]
We stellen voor om de schema:url property los te koppelen van LegaleVerschijningsvorm en enkel met de usage note aan te geven dat dit gebruikt kan worden om door te verwijzen naar een resource waar een Legale Verschijningsvorm staat beschreven.

**Comment by brechtvdv** [comment]
Zie: https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Notificatiebericht

_Hiermee kan doorverwezen worden naar een resource waarop het Notificatiebericht betrekking heeft. Bijvoorbeeld webpagina waar een legale verschijningsvorm vermeld staat._
