### ISSUE TITLE
modaliteit

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#26]
zowel de definitie als het verwachte datatype spreken van "voorwaarde". waarom dan modaliteit?

**Comment by brechtvdv** [comment]
Weggelaten uit model, omdat locatie en tijd op Activiteit (oslo omgevingsvergunning) staat

**Comment by brechtvdv** [comment]
Zie https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Activiteit(omgevingsvergunning)
