### ISSUE TITLE
Plicht = flint:duty?

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#27]
Plicht wordt ontleend aan de flint ontology -> duty.
Het patroon is analoog, maar ik betwijfel of het hetzelfde is.
de FLINT ontologie lijkt zich eerder op het meta-niveau te richten: niet op situatie-specifieke handelingen, feiten, en plichten, maar op de prototypes voor concrete handelingen, feiten, en plichten.
Om deze reden hebben we in de OLSO-omgevingsvergunningen kandidaat-standaard ook beslist hier niet direct van over te nemen.
Quote uit een FLINT paper:
_"It is important to note that instances of the classes Act and Fact are not viewed as concrete acts and facts, but as frames: prototypes of concrete acts and facts as they would be found in a scenario. For example, an act frame can describe applications for a residence permit in general, but not a specific application from an individual."_

**Comment by brechtvdv** [comment]
Vervangen door Verbintenis uit oslo omgevingsvergunning

**Comment by brechtvdv** [comment]
Zie https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Verbintenis
