### ISSUE TITLE
URIs andere definitie

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#32]
Sommige attributen gebruiken zelfde URIs maar hebben andere definities. 

Dit is in strijd met de SEMIC Style Guide rond reuse. Hiervoor worden idealiter usage notes aan toegevoegd of subproperties voor aangemaakt. 

https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html

**Comment by brechtvdv** [comment]
Gekozen voor de aankopen van subproperties, omdat dit ook de SHACL shapes oplost:
https://data.vlaanderen.be/ns/slimmeraadpleegomgeving/#Stuk.gaatOverAdviesvraag
