### ISSUE TITLE
Opmerkingen locatie - Stad Aalst

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#35]
- Het kadastraal perceel is een erg belangrijk object op vlak van besluitvorming bij de lokale besturen. Ik zie wel dat straten en adressen worden meegenomen, maar het kadastraal perceel niet. In het voorbeeld van de presentatie staat specifiek op slide 34 dat er bij geometrie een punt-coördinaat wordt verondersteld?
- Ook hier zal het nodig zijn om lijnen en polygonen en andere geometrie-types mee op te nemen in het datamodel. Misschien is dit nog de bedoeling? Ik geef het maar mee. (LineString, Polygon, Multipoint, enz….)

**Comment by nvdk** [comment]
We zullen de voorbeelden in de README nog up to date brengen, het is zeker mogelijk om deze types van locatie te annoteren. Zie bv https://github.com/Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving?tab=readme-ov-file#kadastrale-gegevens

**Comment by brechtvdv** [comment]
Voorbeeldje aangepast met polygoon: https://github.com/Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving/blob/main/README.md#enkel-co%C3%B6rdinaten
