### ISSUE TITLE
Opmerkingen initiatiefrecht - Stad Aalst

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#36]
- Het initiatiefrecht om een coalitie te vormen
- Het initiatiefrecht van raadsleden (= het recht om punten aan een agenda toe te voegen, het recht om mondelinge en schriftelijke vragen te stellen, het recht om bezoeken te mogen plegen, …) volgens afdeling 2 van het DLB
- Inspraakmogelijkheden van de burger (burgerinitiatief (artikel 271 DLB), voorstellen van burgers, referenda, … (Titel 6 DLB)Ik weet niet of het de bedoeling is om dit in het datamodel allemaal mee te nemen, maar hier is een duidelijke definitie wel nodig. (Ik zou zelf pleiten om het initiatiefrecht voor coalitievorming hier uit te laten….)

**Comment by nvdk** [comment]
De behouden definitie laat expliciet enkel de 2e use case toe:
>   Uitoefening van de bevoegdheden van de mandataris om informatie te bekomen die toegankelijk is via het inzage- en controlerecht, alsook het maken van voorstellen met het oog op uitlokken van besluitvorming.

Het initiatiefrecht om een coalitie te vormen en de inspraakmogelijkheden van de burger zijn dus out of scope van deze klasse.
