### ISSUE TITLE
dereferencing werkt niet voor https://ontology.tno.nl/normengineering/flint 

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#4]
misschien vragen aan de onderzoekers van tno om hun ontologie correct te publiceren?

**Comment by brechtvdv** [comment]
FLINT is weggelaten uit het AP en vervangen door OSLO omgevingsvergunning. Zie https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#NormatieveBepaling , 
https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/#Recht https://data.vlaanderen.be/ns/slimmeraadpleegomgeving/#BehandelingVanAgendapunt.creeertNormatieveBepaling
