### ISSUE TITLE
behandeling agendapunt beëindigt normatieve bepaling

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#41]
https://data.vlaanderen.be/ns/slimmeraadpleegomgeving/#BehandelingVanAgendapunt.beeindigtNormatieveBepaling

wanneer wordt beslist een recht of verbintenis te beëindigen, is dat dan niet een nieuwe normatieve bepaling, in plaats van de beëindiging van een normatieve bepaling?

**Comment by brechtvdv** [comment]
Ik zou de beëeindiging ook als een nieuwe normatieve bepaling beschrijven, maar waarom niet de vorige normatieve bepaling expliciet beëindigen?
Je zou "heft op"/"vervangt"... relaties kunnen toevoegen aan normatieve bepaling, zoals tussen Rechtsgronden: 
https://data.vlaanderen.be/ns/wetgeving#heftOp
Nemen jullie dit verder op in OSLO omgevingsvergunning?

**Comment by PhR-VO** [comment]
In OLSO omgevingsvergunning is al dat wat een rechtshandeling inhoudt gevat onder de superklasse van normatieve bepaling, "Inhoud". Dit kan zijn het bepalen van een bestemming voor een gebied, het verlenen of weigeren van toelating voor een vergunningsplichtige activiteit, het opleggen van voorwaarden, de vaststelling van feiten, het inwilligen van een beroep, het vernietigen van een besluit van een lagere overheid, en ook het intrekken of opheffen van eerdere rechtshandeling. Vaak is dit ook expliciet opgenomen in de inhoud van een rechtshandeling. Soms is het impliciet, dwz, volgt het uit de toepassing (van rechtswege) van bepalingen in hogere regelgeving.

**Comment by brechtvdv** [comment]
Dus ik zie geen probleem bij het beëindigen van een recht of verbintenis. Kan expliciet gemaakt worden met https://data.vlaanderen.be/ns/slimmeraadpleegomgeving/#BehandelingVanAgendapunt.beeindigtNormatieveBepaling , maar kan ook impliciet volgen uit de toepassing van bepalingen in hogere regelgeving.

Ik sluit dit ticket tenzij er nog zaken aangepast moeten worden.
