### ISSUE TITLE
dereferencing werkt niet voor https://eur-lex.europa.eu/eli/eli-draft-legislation-ontology#Participation

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#5]
Waarom geen prov:prov:Association?
Dit heeft hetzelfde patroon en doel, de relatie tussen activiteit en agent qualificeren.
Daarbij is er ook nog prov:role, de relatie tussen Associatie en Rol

**Comment by nvdk** [comment]
De redenatie is dat we besluit-publicatie uitbreiden in deze standaard. Aangezien besluit-publicatie gebaseerd is op ELI stemmen we hier zo veel mogelijk af met ELI en ELI-DL (https://joinup.ec.europa.eu/collection/eli-european-legislation-identifier/solution/eli-ontology-draft-legislation-eli-dl) .

**Comment by gezever** [comment]
Soit, als het niet dereferenced, bestaat het niet.

**Comment by brechtvdv** [comment]
Bert heeft nagevraagd om ELI identifiers dereferenceable te maken. EU is dit volop aan het testen, dus ik verwacht dat dit op korte termijn in orde komt.
