### ISSUE TITLE
http://data.vlaanderen.be/ns/besluit#BehandelingVanAgendapunt , BehandelingVanAgendapuntShape

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-slimmeRaadpleegOmgeving#8]
Naam, range en Kardinaliteit van properties is onduidelijk
Meerdere names, classes en kardinaliteiten zijn gespecifieerd voor eenzelfde shacl:path

```
<https://data.vlaanderen.be/doc/applicatieprofiel/slimmeraadpleegomgeving/ontwerpstandaard/2023-11-06#BehandelingVanAgendapuntShape> a shacl:NodeShape;
  shacl:closed false;
  shacl:property [
    shacl:class crm:E30_Right;
    shacl:description "Recht dat werd beeindigd door de beslissing dat werd genomen tijdens de behandeling van agendapunt."@nl;
    shacl:name "beeindigt"@nl;
    shacl:path prov:invalidated
  ], [
    shacl:class <https://data.vlaanderen.be/ns/slimmeraadpleegomgeving#InitiatiefrechtVraag>;
    shacl:description "Geeft een Initiatiefrechtvraag aan die binnen deze Behandeling Van Agendapunt plaatsvindt."@nl;
    shacl:name "bestaat uit"@nl;
    shacl:path <http://data.europa.eu/eli/eli-draft-legislation-ontology#consists_of>
  ], [
    shacl:class <https://data.vlaanderen.be/ns/slimmeraadpleegomgeving#InitiatiefrechtAntwoord>;
    shacl:description "Geeft een Initiatiefrechtantwoord aan die binnen deze Behandeling Van Agendapunt plaatsvindt."@nl;
    shacl:name "bestaat uit"@nl;
    shacl:path <http://data.europa.eu/eli/eli-draft-legislation-ontology#consists_of>
  ], [
    shacl:class <https://data.vlaanderen.be/ns/besluitvorming#Beslissingsactiviteit>;
    shacl:description "Geeft een Beslissingsactiviteit aan die binnen deze Behandeling Van Agendapunt plaatsvindt."@nl;
    shacl:name "bestaat uit"@nl;
    shacl:path <http://data.europa.eu/eli/eli-draft-legislation-ontology#consists_of>
  ], [
    shacl:class crm:E30_Right;
    shacl:description "Recht dat werd gecreeerd door de beslissing tijdens de behandeling van agendapunt."@nl;
    shacl:name "creeert"@nl;
    shacl:path prov:generated
  ], [
    shacl:class <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#InstancePublicService>;
    shacl:description "Instantie publieke dienstverlening die werd gebruikt voor de behandeling van de agendapunt."@nl;
    shacl:maxCount 1;
    shacl:name "gebruikte"@nl;
    shacl:path prov:used
  ], [
    shacl:class <https://data.vlaanderen.be/ns/dossier#Stuk>;
    shacl:description "Stuk dat werd gebruikt voor de behandeling van de agendapunt."@nl;
    shacl:name "gebruikte"@nl;
    shacl:path prov:used
  ], [
    shacl:class <https://data.europa.eu/eli/ontology#LegalExpression>;
    shacl:description "Een besluit dat is opgemaakt naar aanleiding van de behandeling van het agendapunt."@nl;
    shacl:name "geeft aanleiding tot"@nl;
    shacl:path prov:generated
  ], [
    shacl:datatype xsd:boolean;
    shacl:description "Geeft aan of de bespreking effectief openbaar verlopen is."@nl;
    shacl:maxCount 1;
    shacl:name "openbaar"@nl;
    shacl:path <http://data.vlaanderen.be/ns/besluit#openbaar>
  ];
  shacl:targetClass <http://data.vlaanderen.be/ns/besluit#BehandelingVanAgendapunt> .
```

**Comment by brechtvdv** [comment]
Kardinaliteit is 0..* indien er geen sh:minCount en sh:maxCount meegegeven wordt op de property shape.

Zelfde property paths zouden aangeduid moeten worden met een sh:xone constructie, maar dit kan niet met de huidige toolchain. Als dit echt een issue is, zouden we met subProperties kunnen werken.

**Comment by gezever** [comment]
@brechtvdv 
dit gaat toch een fout geven in de zin van expected class ..., niet?

**Comment by brechtvdv** [comment]
@gezever Inderdaad.. net getest in [shacl playground](https://playground.rdf-ext.org/shacl/#N4Igxg9gbgpgTgQwOYwHIwC4HcJwNYCiAdggEYA2MAJiAFwZwCuMANCFQhggGoLnN0QAAQAOcGADMAlgA8ABDBm05AHgAWGDCNoB6HYoQBbEZQB0uJDoB8c0wB0io8dPlwqE5es3a9WP6awAZnM4SwBGAE4onQAGACYdOLiAWjcJZIBnAE8iLhlkogyAYht7RzFJWTk0jM8NLV0dPywA4ItEmM7YsJ00zLA1GEMEEtsHJ0r5DIGhhDrvRunB4ZDLUvGKlzkZDKp5ht9/INWOmJ6ADQBZABkAZRnh0bKHRVoAIQhSBzkfuQRVeo+HQcLimKDkBAIIhUeAwIimUgwHSFHSIjL8KQYIpvGBqKEw8hSIhIXhEACCKGhCBEjFyNgA3N9fl4DsDOAhTDBGHAICIOVz9ITBVJklREBIMMlKEgpOjOFIIERkoqMBByBAkFkipBCrKMBkAPoQCQ2ADaDn+LJEtT0II54Mh0Nh8MRyIyOnRUkMhngkKoJhgMCQEEMKCgRKQRQAkkRMVJ5ZJxAMMNxEMgbA4ALo/Z5EEBsDJ4kQwXj8GCCCZbQsIMDkfZA5qtE4o6u1p4bZxVMTQeuNRvHdoo7tQdvlTvyHZ7AELQ4tAehU4XG73ZYjdZEBxWm1s0EO/HOhFIqgQMA6akmKRgBPd6Qwcgewne30If2UIMhsMRnQqrDwa1cKkEDcDo4kCZIwjCZIYgANmxXF90JYlSQpOEOBpXJbiLGAbH+Vs61QCAYUw6kYEZIgfjw2hawgDJqDkCQ+FosiKLxWtaG7Ys4AwLI5HNcjfko2sEAyDJpy0bc7TBCF93EF0kRbR8fTTV9A2DUMYHDYlo1jDB410xMYGTVNISQKxmIE1i6xhaY4CkERdMVOQ7BAABxQMJQUOE5BjOMEwkJMNCgNMkD+KE5CoKQYDkUgiSILyYQALyinE8SdRCQtJOQUKpdCMDkExIX1TSqAwexhCIchzJYms6xIH0nJANEuE4ORGExZyhAqqq5EovkMDUMSgUkrkeT5TlGGFYVRXFSVpVlCEHKVFU1Q1LUdQyPVDWNKwmUzczetG+BuN4plqrYoSRMGiT2Skx0YVkw83QfL0lL9AN33UzTIx83S/ICjAyVyHBcCoMzTp6yzaGssBbPshVyOctzJDywNyJ+vTIv8wyNChbAIBBn5HXCyLoti+KYCSuQUoQiM5Ey7K0NpPKCs4DJitKjquvByi6qi5ymsK1r2vKyruchvqBqtRphu5Xl+Qmu8pCmsUEAlKUg3m+VFWVXIVs1bVFQ2jJ9SNE1dv2yGuFCTAAGEIUuqXbRuvcnQe10UTRDEsWptKI2QylGbpWx8xAKA+CkEF4duTBdOJDI6FASBYEQFA6AY8haLYGFSEYJA08Y1h2EwBApAz/OM8Lhga3LWh09ogBfeugA=) dat meerdere gelijke property paths met verschillende targetClass niet conform zijn.

Dit zou eigenlijk een `sh:or` moeten zijn: [playground](https://playground.rdf-ext.org/shacl/#N4Igxg9gbgpgTgQwOYwHIwC4HcJwNYCiAdggEYA2MAJiAFwZwCuMANCFQhggGoLnN0QAAQAOcGADMAlgA8ABDBm05AHgAWGDCNoB6HYoQBbEZQB0uJDoB8c0wB0io8dPlwqE5es3a9WP6awAZnM4SwBGAE4onQAGACYdOLiAWjcJZIBnAE8iLhlkogyAYht7RzFJWTk0jM8NLV0dPywA4ItEmM7YsJ00zLA1GEMEEtsHJ0r5DIGhhDrvRunB4ZDLUvGKlzkZDKp5ht9/INWOmJ6ADQBZABkAZRnh0bKHRVoAIQhSBzkfuQRVeo+HQcLimKDkBAIIhUeAwIimUgwHSFHSIjL8KQYIpvGBqKEw8hSIhIXhEACCKGhCBEjFyNgA3N9fl4DsDOAhTDBGHAICIOVz9ITBVJklREBIMMlKEgpOjOFIIERkoqMBByBAkFkipBCrKMBkAPoQCQ2ADaDn+LJEtT0II54Mh0Nh8MRyIyOnRUkMhngkKoJhgMCQEEMKCgRKQRQAkkRMVJ5ZJxAMMNxEMgbA4ALo/Z5EEBsDJ4kQwXj8GCCCZbQsIMDkfZA5qtE4o6u1p4bZxVMTQeuNRvHdoo7tQdvlTvyHZ7AELQ4tAehU4XG73ZYjdZEBxWm1s0EO/HOhFIqgQMA6akmKRgBPd6Qwcgewne30If2UIMhsMRnQqrDwa1cKkEDcDo4kCZIwjCZIYgANmxXF90JYlSQpOEOBpXJbiLGAbH+Vs61QCAYUw6kYEZIgfjw2hawgDJqDkCQ+FosjKNwOQAAomTkc1yN+SjawQDIMmnLRtztMEIX3cQXSRFtHx9NNX0DYNQxgcNiWjWMMHjLTExgZNU0hJArDI345EomFpjgKQRC0xU5DsEAAHFAwlBQ4TkGM4wTCQkw0KA0yQP4oTkKgpBgORSCJIh3JhAAvcKcTxJ1EMC0k5BQql0IwOQTEhfU1KoDB7GEIhyBM3i8VrWgSB9eyQDRLhODkRhMQcoRSvKijKrrPkMDUYSgTErkeT5TlGGFYVRXFSVpVlCFbKVFU1Q1LUdQyPVDWNKwmUzJluNMviIUEgbRPZcTHRhKTDzdB8vXkv0A3fFS1MjTytO83yMDJXIcFwKhjM4szutoCywCsmyFXIhznMkbLA3It7tLCny9I0KFsAgP6fkdEKwoiqKYpgeK5EShCIzkNKMrQ2lstyzgMgKoq2o6wHKJq8KHIavLmtakqytZ4Hev6q1GiG7leX5ca7ykSaxQQCUpSDOb5UVZVcmWzVtUVdaMn1I0TR2hwAEpysorhQkwABhI6hJF20zr3J0rtdFE0QxLFSeSiNkMpam6VsfMQCgPgpBBSHbkwLTiQyOhQEgWBEBQOgGPIWi2BhUhGCQZPGNYdhMAQKRU5z1O84YGty1oFPaIAXxroA===) 

Ik zal subproperties maken, maar in de usageNote zetten dat de generieke property gebruikt moet worden
